version: "3.9"
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      monitoring:
        aliases:
          - postgresdb
  service_demo:
    build: .
    restart: always
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/postgres
    depends_on:
      - postgresdb
    networks:
      monitoring:
        aliases:
          - spring-app
networks:
  monitoring:

