version: "3.9"
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      monitoring:
        aliases:
          - postgresdb
  service_demo:
    build: .
    restart: always
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/postgres
    depends_on:
      - postgresdb
    networks:
      monitoring:
        aliases:
          - spring-app
  grafana:
    build: './scripts/config/grafana'
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./scripts/grafana:/var/lib/grafana
      - ./scripts/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./scripts/prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring:

