spring:
  datasource:
    username: postgres
    password: password
    url: 'jdbc:postgresql://localhost:5432/postgres'
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
