create table if not exists person
(
    id   bigint generated by default as identity
        constraint pk_person
            primary key,
    name text,
    age  integer
);

alter table person
    owner to postgres;

create unique index table_name_id_uindex
    on person (id);

INSERT INTO public.person (id, name, age) VALUES (1, 'vasya', 12);
INSERT INTO public.person (id, name, age) VALUES (2, 'oleg', 14);
INSERT INTO public.person (id, name, age) VALUES (3, 'pupa', 13);
INSERT INTO public.person (id, name, age) VALUES (4, 'lupa', 21);
INSERT INTO public.person (id, name, age) VALUES (6, 'six', 6);